// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://earkfmqybymzmwnutdpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcmtmbXF5Ynltem13bnV0ZHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTE3MjYsImV4cCI6MjA2NDYyNzcyNn0.z1laYigYKPq7uSlPhq1vr5D2YECaocc2eip-XThMI0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);